### PR TITLE
ENH: release and install library 0.4.0

### PR DESCRIPTION
**Pull request by nrwslac**
Need review to push library release.

### CODE REVIEW

**Comment by klauer** [comment]
I think the library release process might be a bit different than what you're doing here, and should be routed through `tc-release` like we do normal PLC projects: https://confluence.slac.stanford.edu/display/PCDS/How+to+Release+and+Install+Vacuum+PLC+Library

**Comment by nrwslac** [comment]
reviewing link.

**Comment by klauer** [comment]
I might not have actually gone through the process myself, I forget... 😁  
@ZLLentz, does the process you follow match the link above from Jing?

**Comment by nrwslac** [comment]
I'll close this pull request. Follow procedure outline in link.

**Comment by nrwslac** [comment]
used `tc-release` and vacuum library how to release notes instead of this.

**Comment by ZLLentz** [comment]
Confirming that you did the correct procedure as far as I can tell
For bonus points you can come back later and include release notes at https://github.com/pcdshub/lcls-twincat-optics/releases/tag/v0.4.1 so that we know what was added/fixed in that version

**Pull request closed without merging**
